### ISSUE TITLE
Add sx prop to top level components

### ISSUE THREAD

**Issue by bryanjtc** [NicholasMata/mui-file-upload#1]
Allow styling components like MultiFileUploadProps and SingleFileUploadProps by using the sx prop to customise the FileDropzone and the FileUpload

**Comment by NicholasMata** [comment]
With the latest version v1.0.0-alpha.4 sx is now available on the top level components

**MultiFileUpload**
```
<MultiFileUpload
  sx={{
    dragZoneSx: (state) => { border: state.dragActive ? 'green' : 'blue'}
  }}
  ...
/>
```
 
**SingleFileUpload**
```
<SingleFileUpload
  sx={{
    dragZoneSx: (state) => { border: state.dragActive ? 'green' : 'blue'}
  }}
  ...
/>
```
