### ISSUE TITLE
Add custom labels to top level components

### ISSUE THREAD

**Issue by bryanjtc** [NicholasMata/mui-file-upload#2]
Adding props to change the text of the file upload and file drop zone components makes adding i18n support easier.

**Comment by NicholasMata** [comment]
@bryanjtc  Thanks for your interest and feedback. I have released v1.0.0-alpha.4 and added examples of this in storybook.

Custom text can be done like this

**MultiFileUpload**
```
<MultiFileUpload
  body={<FileDropzoneBody dropTitle={<Typography2>Custom drop text here</Typography2>} title="Custom text here"/>}
  ...
/>
```
 
**SingleFileUpload**
```
<SingleFileUpload
  body={<FileDropzoneInputBody dropTitle="Custom drop text here" title="Custom text here"/>}
  ...
/>
```
