### ISSUE TITLE
'MultiFileUpload' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by leneos** [NicholasMata/mui-file-upload#5]
Hi! I'm having an error while using MultiFileUpload and SingleFileUpload 
**'MultiFileUpload' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.ts(2786)**

i guess the problem is that ReactNode can be undefined when undefined is a wrong jsx element.
i propose changing all ReactNode type to JSX.Element type

**Comment by leneos** [comment]
#6

**Comment by NicholasMata** [comment]
Fixed in v1.0.0-alpha.6
